### ISSUE TITLE
Skąd takie dziwne nazewnictwo?

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#1]
http://www.oracle.com/technetwork/java/codeconventions-135099.html

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/8197613026007ebdff448ce06b1b1b4fc90cc8eb/kodilla-testing/src/main/java/com/kodilla/testing/library/BookLibrary.java#L13

**Comment by urbanex** [comment]
chciałem wyraźnie widzieć kiedy operuje metodą z klasy a kiedy z interfejsu. Wg mnie to dublowanie nazw tych, wszakże rożnych, metod przez autora wpływa na mniejsza czytelność kodu i zmniejsza zorientowanie się co tam się dzjjee, a przynajmniej dla kogoś na moim etapie. Wiec to dziwne nazewnictwo to tylko dla mnie :)

**Comment by TomaszZupka** [comment]
Potem takie dublowanie nazw występuje w projektach - często metoda w serwisie, ma taką samą nazwę jak ta w kontrolerze itp.
Na początku jak na to zerknąłem pomyślałem po prostu co tu się stało, czy materiały kodilli jakoś się zmieniły od mojego ostatniego czytania :P

**Comment by TomaszZupka** [comment]
Widzę, że nazewnictwo pozostało, teraz możemy jeszcze na to przymknąć oko, ale w przyszłym kodzie nie pisze się takich rzeczy ;)

**Comment by urbanex** [comment]
tak, poproszę :) jeszcze będę wracać do tego na pewno i jako taki wzorzec mi się przyda

**Comment by urbanex** [comment]
może jakbym wiesz, miał lepiej podkolorowaną składnię to nie potrzebowałbym tej pomocy naukowej. W eclipsie miałem taki motyw wybrany, z którego więcej rzeczy widać było na pierwszy rzut oka. Pewno w intellij można zmieniać też, zaraz poszukam :)

**Comment by TomaszZupka** [comment]
to zamykam
