### ISSUE TITLE
Zbędne komplikowanie :)

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#11]
Początek rozwiązanie a jednym strumieniem, nie można prościej, tzn. zamiast:
```
IntStream.range(0, project.getTaskLists().size())
                .mapToObj(n -> project.getTaskLists().get(n))
```
tak:
```
project.getTaskLists().stream()
```
tak zrobiłeś w wersji z dwoma strumieniami :)

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/45810df036ca47e65e0412e04426ea8e738fc4e8/kodilla-stream/src/test/java/com/kodilla/stream/portfolio/BoardTestSuite.java#L152

**Comment by urbanex** [comment]
kurde, byłem przekonany, że average() jest tylko w IntStreamie ;) w sumie i tak pozniej robie mapToLong, wiec juz kumam - w LongStreamie jest average.
