### ISSUE TITLE
Kropki

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#14]
Taki drobiazg, kropki dajemy odwrotnie:
```
List<Flight> flightsFrom = flights.stream()
                .filter(flight -> flight.getDepartureAirport().equals(airport))
                .collect(Collectors.toList());
```

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/a2d4665db7b17720005a606b048ced81615e4c32/kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/airline/FlightsDatabase.java#L42

**Comment by urbanex** [comment]
ale gafa ;D
