### ISSUE TITLE
Również nagle zmiana nazewnictwa

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#5]
Przyjęta konwencja w testach powyżej jest bez podkreśleń :)
Nazwy testów poniżej ta sama uwaga.

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/8197613026007ebdff448ce06b1b1b4fc90cc8eb/kodilla-testing/src/test/java/com/kodilla/testing/library/BookDirectoryTestSuite.java#L91

**Comment by urbanex** [comment]
a te kreski dolne to jakiś ciężki grzech? ;) 0 tak mi się jakoś zlewało z Of, Of0 troche takie ofo więc sobie to uczytelniłem, -5 dioptrii robi swoje, zaraz pozmieniam

**Comment by TomaszZupka** [comment]
nie jest to ciężki grzech, w niektórych projektach czasami się tak robi (tylko w nazwach testów!) tylko trzeba przyjąć jakąś konwencję, a nie żeby na górze bez, na dole z :)

**Comment by urbanex** [comment]
rozumiem, pierwsze trzy testy to dzieło kodilli - jakbym sam je pisał to zapewne całość byłaby w jednej konwencji
