### ISSUE TITLE
Dodatkowa weryfikacja

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#6]
Tak się zastanawiam czy skoro już tak przekazujemy tego użytkownika może byśmy zrobili tak:
`when(libraryDatabaseMock.listBooksInHandsOf_INTERFACE_LibraryDatabase(any(LibraryUser.class)))`
potem w when przekazali tego stworzonego wcześniej i następnie w then dodatkowo:
`verify(libraryDatabaseMock, times(1)).listBooksInHandsOf_INTERFACE_LibraryDatabase(libraryUser);`

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/8197613026007ebdff448ce06b1b1b4fc90cc8eb/kodilla-testing/src/test/java/com/kodilla/testing/library/BookDirectoryTestSuite.java#L101

**Comment by urbanex** [comment]
w sumie przez chwile kombinowałem i chciałem jakoś mieć tego usera z wykorzystaniem anyString, bo to głupio wyglądało: `when(libraryDatabaseMock.listBooksInHandsOf_INTERFACE_LibraryDatabase(new LibraryUser(anyString(), anyString(), anyString())))` tak myslalem, że moze jakos latwiej bedzie mozna i że coś podpowiesz :)

**Comment by TomaszZupka** [comment]
Skoro dodałeś potem tego verify do testListBooksInHandsOf1Book oraz testListBooksInHandsOf5Books to warto tutaj również w mocku przyjąć jakiegokolwiek użytkownika: any(LibraryUser.class)

**Comment by urbanex** [comment]
racja!

**Comment by urbanex** [comment]
poprawione
