### ISSUE TITLE
Do czego ten set?

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#7]
Nie możemy założyć, że kraje na świecie się nie powtarzają :)

https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/b7ab4d885c3a654d1f17a98754178cb1ead5cea3/kodilla-stream/src/main/java/com/kodilla/stream/world/World.java#L18

**Comment by urbanex** [comment]
no wlasnie celowo tutaj dałem set, bo Rosje wrzuciłem zarówno do Azji jak i Europy i jakbym chcial policzyc ludnosc swiata, to przeciez policze Rosjan dwukrotnie, dlatego dalem seta zeby rosja pojawila sie tylko raz, zly tok rozumowania?

**Comment by TomaszZupka** [comment]
Może tak być ale chęć nie brania duplikatów lepiej wyraża:
```
.distinct()
```
jest tak samo używane w sql (bazy danych) aby nie brać duplikatów :)
