### ISSUE TITLE
Wszędzie ci azjaci :)

### ISSUE THREAD

**Issue by TomaszZupka** [urbanex/jacek-urbanowski-kodilla-java#9]
Nie chcę być rasistą ale czemu wszędzie mają być ci azjaci :)
https://github.com/urbanex/jacek-urbanowski-kodilla-java/blob/b7ab4d885c3a654d1f17a98754178cb1ead5cea3/kodilla-stream/src/test/java/com/kodilla/stream/world/WorldTestSuite.java#L50

**Comment by urbanex** [comment]
omg... +1:  już poprawiam
